include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    # Falha o build se houver TODO/FIXME não resolvido em release.
    todo: ignore

linter:
  rules:
    - prefer_final_locals
    - prefer_const_constructors
    - avoid_print
    - public_member_api_docs
